// All tunable game parameters
export const PLAYER = {
  MOVE_SPEED: 12,
  SPRINT_SPEED: 18,
  SPRINT_MULTIPLIER: 1.6,
  JUMP_FORCE: 8,
  MAX_HEALTH: 150,
  SPAWN_INVULNERABILITY: 3,
  HEIGHT: 1.8,
  RADIUS: 0.5,
  MOUSE_SENSITIVITY: 0.002,
  DECELERATION: 10,
  ACCELERATION: 40,
  HEAD_BOB_SPEED: 12,
  HEAD_BOB_AMOUNT: 0.04,
  DASH_SPEED: 28,
  DASH_DURATION: 0.15,
  DASH_COOLDOWN: 1.2,
};

export const WEAPONS = {
  PISTOL: {
    name: 'Pistol',
    damage: 15,
    fireRate: 0.3,
    ammo: Infinity,
    maxAmmo: Infinity,
    magSize: Infinity,
    reloadTime: 0,
    spread: 0.01,
    auto: false,
    recoil: 0.02,
    color: 0x888888,
  },
  SHOTGUN: {
    name: 'Shotgun',
    damage: 8,
    pellets: 8,
    fireRate: 0.8,
    ammo: 30,
    maxAmmo: 30,
    magSize: 6,
    reloadTime: 2.0,
    spread: 0.08,
    auto: false,
    recoil: 0.06,
    color: 0xaa6633,
  },
  ASSAULT_RIFLE: {
    name: 'Assault Rifle',
    damage: 10,
    fireRate: 0.1,
    ammo: 120,
    maxAmmo: 120,
    magSize: 30,
    reloadTime: 1.5,
    spread: 0.02,
    spreadIncrease: 0.005,
    maxSpread: 0.08,
    auto: true,
    recoil: 0.015,
    color: 0x444444,
  },
  ROCKET_LAUNCHER: {
    name: 'Rocket Launcher',
    damage: 80,
    splashDamage: 40,
    splashRadius: 5,
    fireRate: 1.5,
    ammo: 12,
    maxAmmo: 12,
    magSize: 4,
    reloadTime: 2.5,
    spread: 0,
    projectileSpeed: 30,
    auto: false,
    recoil: 0.08,
    color: 0x335533,
  },
};

export const ENEMIES = {
  GRUNT: {
    name: 'Grunt',
    health: 30,
    damage: 8,
    speed: 6,
    size: { x: 0.6, y: 0.8, z: 0.6 },
    color: 0xff2255,
    emissive: 0xff1133,
    points: 100,
    attackRange: 1.5,
    attackCooldown: 1.2,
  },
  SHOOTER: {
    name: 'Shooter',
    health: 60,
    damage: 8,
    speed: 4,
    size: { x: 0.7, y: 1.2, z: 0.7 },
    color: 0x00ccff,
    emissive: 0x0088cc,
    points: 200,
    attackRange: 25,
    preferredRange: 12,
    attackCooldown: 2.0,
    projectileSpeed: 15,
  },
  TANK: {
    name: 'Tank',
    health: 150,
    damage: 30,
    speed: 3,
    chargeSpeed: 12,
    size: { x: 1.2, y: 1.5, z: 1.2 },
    color: 0x22ff88,
    emissive: 0x11cc55,
    points: 500,
    attackRange: 15,
    chargeCooldown: 4,
    chargeDistance: 3,
  },
  EXPLODER: {
    name: 'Exploder',
    health: 20,
    damage: 45,
    speed: 8,
    size: { x: 0.5, y: 0.6, z: 0.5 },
    color: 0xff6600,
    emissive: 0xff4400,
    points: 150,
    attackRange: 2.5,
    attackCooldown: 99,
    explosionRadius: 4,
  },
  TELEPORTER: {
    name: 'Teleporter',
    health: 45,
    damage: 15,
    speed: 5,
    size: { x: 0.5, y: 1.0, z: 0.5 },
    color: 0xaa44ff,
    emissive: 0x8822cc,
    points: 300,
    attackRange: 3,
    attackCooldown: 1.5,
    teleportCooldown: 3,
    teleportRange: 8,
  },
};

export const ARENA = {
  SIZE: 60,
  WALL_HEIGHT: 8,
  COVER_COUNT: 18,
  FOG_NEAR: 20,
  FOG_FAR: 70,
  FOG_COLOR: 0x0a0a1e,
};

export const WAVES = {
  BASE_GRUNTS: 4,
  GRUNT_INCREMENT: 3,
  SHOOTER_UNLOCK_WAVE: 2,
  TANK_UNLOCK_WAVE: 4,
  EXPLODER_UNLOCK_WAVE: 3,
  TELEPORTER_UNLOCK_WAVE: 5,
  BOSS_WAVE_INTERVAL: 5,
  HEALTH_SCALE_START_WAVE: 3,
  HEALTH_SCALE_PER_WAVE: 0.12,
  BREATHER_TIME: 3,
  SPAWN_STAGGER: 0.25,
  WAVE_CLEAR_BONUS_MULTIPLIER: 1500,
};

export const SCORING = {
  COMBO_TIMEOUT: 4,
  COMBO_INCREMENT: 0.5,
  HEADSHOT_MULTIPLIER: 2.5,
};

export const POWERUPS = {
  DROP_CHANCE: 0.35,
  FLOAT_HEIGHT: 0.8,
  BOB_SPEED: 2,
  BOB_AMOUNT: 0.3,
  ROTATE_SPEED: 1.5,
  HEALTH_AMOUNT: 35,
  SPEED_DURATION: 7,
  SPEED_MULTIPLIER: 2,
  DAMAGE_DURATION: 7,
  DAMAGE_MULTIPLIER: 2.5,
  SHIELD_AMOUNT: 60,
  TIMESLOW_DURATION: 5,
  TIMESLOW_FACTOR: 0.35,
  SIZE: 0.5,
};

export const PHYSICS = {
  GRAVITY: -20,
  FIXED_TIMESTEP: 1 / 60,
  MAX_SUB_STEPS: 3,
};

export const EFFECTS = {
  MUZZLE_FLASH_DURATION: 0.05,
  BULLET_TRAIL_DURATION: 0.1,
  HIT_MARKER_DURATION: 0.15,
  KILL_MARKER_DURATION: 0.25,
  DAMAGE_VIGNETTE_DURATION: 0.3,
  SCREEN_SHAKE_DURATION: 0.2,
  PARTICLE_COUNT: 500,
};

export const DANGER_ZONES = {
  WARNING_TIME: 1.5,
  ACTIVE_TIME: 0.5,
  DAMAGE: 25,
  RADIUS: 4,
  MIN_WAVE: 3,
  INTERVAL: 8,
};

export const ULTIMATE = {
  KILLS_TO_CHARGE: 15,
  RADIUS: 20,
  DAMAGE: 200,
  KEY: 'KeyF',
};
